# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_cryptomkt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='fecha',
            field=models.DateTimeField(default=1, verbose_name='fecha consulta'),
            preserve_default=False,
        ),
    ]
